language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake libboost-all-dev libeigen3-dev libhdf5-serial-dev libvtk5-dev

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE:STRING=Release -DUSE_SYSTEM_Boost:BOOL=ON -DUSE_SYSTEM_Eigen:BOOL=ON -DUSE_SYSTEM_HDF5:BOOL=ON -DUSE_SYSTEM_VTK:BOOL=ON ../superbuild
  - make -j2
