language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:zarquon42/precise-backports -y
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake libboost1.55-dev libboost1.55 libeigen3-dev libhdf5-serial-dev libvtk5-dev libinsighttoolkit4-dev

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE:STRING=Release -DUSE_SYSTEM_Boost:BOOL=ON -DUSE_SYSTEM_Eigen:BOOL=ON -DUSE_SYSTEM_HDF5:BOOL=ON -DUSE_SYSTEM_VTK:BOOL=ON -DUSE_SYSTEM_ITK:BOOL=ON ../superbuild
  - make -j2
